app = "chatemmain-old-darkness-6967"

primary_region = "sjc"

[env]
  PORT = "8080"

[build]
  image = ""

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
